### ISSUE TITLE
Auto complete support in SQL editor

### ISSUE THREAD

**Issue by wj-c** [MotherDuck-Open-Source/metabase_duckdb_driver#13]
Thanks for providing this plugin. I wonder how can I configure it to support duckdb sql syntax auto completion in the editor?

**Comment by elefeint** [comment]
@wj-c we meant to test how well autocomplete works -- did you figure it out?

**Comment by wj-c** [comment]
> @wj-c we meant to test how well autocomplete works -- did you figure it out?

What I care more about is autocompletion of table and view name that follow from clause.

I find out that while in memory db does not support it, duckdb from a file actually supports it.

So it's great, problems solved for me :)

**Comment by elefeint** [comment]
Thank you!
