### ISSUE TITLE
Add support for DuckDB 1.1.0

### ISSUE THREAD

**Issue by dersteppenwolf** [MotherDuck-Open-Source/metabase_duckdb_driver#17]
I would like to request support for the latest release of DuckDB, version 1.1.0 and 1.1.1 This new version includes several important updates and optimizations that could benefit many users. Adding support for DuckDB 1.1.0 would be a valuable addition to the project, ensuring compatibility with the latest features and improvements.

**Comment by hrl20** [comment]
This is coming soon!
