### ISSUE TITLE
Support setting configuration on startup

### ISSUE THREAD

**Issue by hmac** [MotherDuck-Open-Source/metabase_duckdb_driver#19]
Thanks for this driver, it's very useful!

There are a few config options I'd like to set in duckdb when the connection is opened, specifically:

- `memory_limit`, to avoid my container being killed by a large query
- `azure_transport_option_type`, which works around a problem with the Azure extension

It would be great if there was a way to specify some SQL commands to run at startup, similar to `.duckdbrc`.

**Comment by hrl20** [comment]
added support for these parameters. still exploring options for supporting `.duckdbrc`-like functionality.
