### ISSUE TITLE
Unable to view tables via Metabase but only via raw SQL query

### ISSUE THREAD

**Issue by activatedgeek** [MotherDuck-Open-Source/metabase_duckdb_driver#21]
I have a DuckDB database generated with DuckDB 1.1.0 via SQL Alchemy in Python.

I am loading the DuckDB driver for Metabase with the following Dockerfile,
```
FROM openjdk:19-buster

ENV MB_PLUGINS_DIR=/home/plugins/

ADD https://downloads.metabase.com/v0.50.32/metabase.jar /home

ADD https://github.com/MotherDuck-Open-Source/metabase_duckdb_driver/releases/download/0.2.10/duckdb.metabase-driver.jar /home/plugins/

RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

CMD ["java", "-jar", "/home/metabase.jar"]
```

I am able to add the DuckDB database to Metabase, but as soon I try to access my tables, I see the following error:

![Screenshot 2024-11-08 at 1 17 28 PM](https://github.com/user-attachments/assets/3a0c36db-66dd-4b02-a6ff-ded758967c64)

Oddly, when I start a new raw SQL query instead, I am able to successfully see all the rows.

![Screenshot 2024-11-08 at 1 18 58 PM](https://github.com/user-attachments/assets/6c1c1098-a403-4c49-bb90-579ca2db205a)

Can you help me figure this out please?

**Comment by hrl20** [comment]
I'm not sure if your table was created before or after the connection. If after, have you resynced the schema in Metabase since adding the table? https://www.metabase.com/docs/latest/databases/sync-scan

**Comment by activatedgeek** [comment]
The table was created before the connection via a separate script. I did try to resync the schema from the admin dashboard but the error still remains.

As a stop gap solution, I created a Metabase Model by running a raw SQL query, and I am able to continue as usual from there.

**Comment by hrl20** [comment]
i see. do you mind sharing what you see for that database and that table (if exists) in the Table Metadata tab in the admin console? 

Also, the underlying duckdb SQL query to figure out the fields/columns of that table is going to be something like, 
```
select * from information_schema.columns where table_name = 'movies' and table_schema = 'main'
```

you can try running it and see if the expected columns are returned.

**Comment by bassemsuhail** [comment]
Hello @hrl20  i have the same issue... did you find any solution to see the list of tables without use SQL query?
Thank you

**Comment by hrl20** [comment]
hi @bassemsuhail thanks for the report. do you see anything when you directly run the query?
```
select * from information_schema.columns where table_name = '<your table name>' and table_schema = '<your schema>'
```

**Comment by bassemsuhail** [comment]
Hi @hrl20 yes i can see all the list of tables and i can run it,, but if i want to use a question i can't see anything

**Comment by hrl20** [comment]
@bassemsuhail  I suspect it has to do with the table containing some JSON columns (previously DuckDB would type the column as VARCHAR) which wasn't handled. If that's the case, could you try the latest driver I just released?

**Comment by bassemsuhail** [comment]
@hrl20  i think my case the same i have some tables containing some JSON columns.
i will be so thankful if you put the driver link..

**Comment by bassemsuhail** [comment]
@hrl20 thank you i download the drive and its working i can see all tables now.. 
but when i try to write new data on the duckdb file by python code this error appears:

**duckdb.duckdb.IOException: IO Error: File is already open in
C:\Program Files\Java\jdk-11\bin\java.exe (PID 15168)**
 
i just open it on metabase

**Comment by hrl20** [comment]
@bassemsuhail i believe this issue is a [DuckDB limitation](https://duckdb.org/docs/connect/concurrency.html#handling-concurrency), see previous discussion here: https://github.com/MotherDuck-Open-Source/metabase_duckdb_driver/issues/22 

Closing this issue thread since the reported issue has been resolved.
