### ISSUE TITLE
Request for a Non-Locking PID Version of DuckDB

### ISSUE THREAD

**Issue by yface504** [MotherDuck-Open-Source/metabase_duckdb_driver#22]
My current setup involves synchronizing MySQL on the host machine to DuckDB. However, when operating with Metabase, Metabase creates a PID lock that prevents MySQL from writing to DuckDB.

 I hope for a version or configuration option in new that would avoid this PID locking issue, allowing MySQL to write to DuckDB seamlessly.

**Comment by elefeint** [comment]
Writing to the same DuckDB file and reading from it simultaneously from a different process is not possible (see DuckDB [docs](https://duckdb.org/docs/connect/concurrency.html#handling-concurrency)).
If your requirement is to both write and read at the same time, you might consider using [MotherDuck](https://app.motherduck.com/), which is a Cloud based data warehouse based on DuckDB instead.
